name: flutter_experiment
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  http: ^1.2.2
  html: ^0.15.5
  intl: ^0.19.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  tutorial_coach_mark: ^1.2.12
  persistent_bottom_nav_bar_v2: ^5.3.1
  persistent_bottom_nav_bar: ^6.2.1
  image: ^4.5.2
  flutter_svg: ^2.0.16
  icons_plus: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_simple_calculator: ^2.3.0
  syncfusion_flutter_charts: ^20.4.50


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
